# Generated by Django 4.1 on 2022-10-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
