# Generated by Django 4.1 on 2022-10-12 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_delete_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorit_status', models.BooleanField(default=False)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.favorite')),
            ],
        ),
        migrations.AddField(
            model_name='favorite',
            name='advertisements',
            field=models.ManyToManyField(related_name='favorites', through='advertisements.FavoriteAdv', to='advertisements.advertisement'),
        ),
    ]
