# Generated by Django 4.1 on 2022-10-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_favorite_favoriteadv_favorite_advertisements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteadv',
            name='advertisement',
        ),
        migrations.RemoveField(
            model_name='favoriteadv',
            name='favorite',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='FavoriteAdv',
        ),
    ]
