# Generated by Django 4.1 on 2022-10-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_remove_favoriteadv_advertisement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ManyToManyField(related_name='advertisements', through='advertisements.AdvFav', to='advertisements.advertisement')),
            ],
        ),
        migrations.AddField(
            model_name='advfav',
            name='favorites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.favorite'),
        ),
    ]
