# Generated by Django 4.1 on 2022-10-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_advfav_favorite_advfav_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorite',
        ),
        migrations.DeleteModel(
            name='AdvFav',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
