# Generated by Django 4.1 on 2022-09-03 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(null=True, unique=True, upload_to='')),
                ('release_date', models.DateField(default=datetime.datetime.now)),
                ('lte_exists', models.BooleanField(null=True)),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='name')),
            ],
        ),
    ]
